{{- if .Values.k8s_use_secrets.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "app-deploy-template.fullname" . }}-k8s-secret  
spec:
  provider: aws
  parameters: 
    objects: |
      {{- range $key, $val := .Values.k8s_secrets }}
      - objectName: "{{ $val.key }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range $key, $val := $val.paths }}
          - path: {{ $val.pathname }}
            objectAlias: {{ $val.pathalias }}
          {{- end}}
      
      {{- end }}            

  # Create k8s secret. It requires volume mount first in the pod and then sync.
  #- objectName: <objectName> or <objectAlias>
  secretObjects:
    {{- range $key, $val := .Values.k8s_secrets }}
    - secretName: {{ $val.name }}
      type: Opaque
      data:
        {{- range $key, $val := $val.paths }}
        - objectName: {{ $val.pathalias }}
          key: {{ $val.key }}
        {{- end }}
    {{- end }}
{{- end }}
