{{- if and (.Values.istio.enabled)  (.Values.istio.jwt.enabled) -}}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "app-deploy-template.serviceAccountName" . }}
  labels:
    {{- include "app-deploy-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app-deploy-template.selectorLabels" . | nindent 6 }}
  jwtRules:
  - issuer: {{ .Values.istio.jwt.issuer }}
    jwksUri: {{ .Values.istio.jwt.jwksUri }}
{{- end }}