{{- if .Values.istio.enabled -}}
{{- $fullName := include "app-deploy-template.fullname" . -}}
{{- $svcPort := .Values.service.servicePort.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app-deploy-template.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- range .Values.istio.virtualservice.hosts }}
    - {{.host}}
    {{- end }}
  gateways:
  - {{ $fullName }}
  http:
    {{- range .Values.istio.virtualservice.hosts }}
    - match:
        {{- range .paths }}
        - uri:
            prefix: {{ .path | quote }}
        {{- end }}
      route:
        - destination:
            host:  {{ $fullName }}
            port:
              number: {{ $svcPort }}
    {{- end }}
{{- end }}